# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d421f94b8710d39177081602c94ec285ac3bda66da045919607c2daf8b0318f798d96015213721ebfcc3f457303064d6da414a6fe87f074fa58e628c033e507f

test:
  secret_key_base: 51446c270fa9967ebba6fa2d205827b756e27943e36564912dc04e72a844cd85e4792c6eff0bc8bd28b1727cc86336aec69acd00b9f5343ca03e1adb6bf93af6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
